- name: Delete a10_scaleout_cluster_service_config_template example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_scaleout_cluster_service_config_template instance
    a10_scaleout_cluster_service_config_template:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_template





